### ISSUE TITLE
no edit command

### ISSUE THREAD

**Issue by yedajiang44** [pmahend1/resxpress#88]
I cannot associate the resx file and cannot find the edit viewer(vscode is last version)

![image](https://github.com/pmahend1/resxpress/assets/25813145/49f63da6-123c-4f25-9141-6bbcb13d6e9e)

**Comment by pmahend1** [comment]
If you want to open a resx file through **ResXpress**
- Right click on the resx file.
- Click **Open With...**
- Choose **ResXpress Editor**

![image](https://github.com/pmahend1/resxpress/assets/21352870/c3a59d2c-020f-4fa2-bf02-09542e6091e1)

If you want to make it default editor for resx then,

Click on Configure default provider '*.resx' and choose **ResXpress Editor**
![image](https://github.com/pmahend1/resxpress/assets/21352870/b1abc9aa-4194-41a9-9e44-178193c50da6)
