### ISSUE TITLE
Saving is deleting all the changes

### ISSUE THREAD

**Issue by dogruis** [pmahend1/resxpress#91]
When trying to save my change. It ends up deleting everything.
I use vscode Version: 1.91.0 on mac os Sonoma 14.5.

**Comment by pmahend1** [comment]
Thanks for reporting @dogruis 
Sorry for the delayed response. Could you please share logs if you have any.

**Comment by pmahend1** [comment]
v 7.0.0 should fix this. Please open a new issue with logs if issue persists.
