### ISSUE TITLE
Allow underscore char in Keys

### ISSUE THREAD

**Issue by manugparedes** [pmahend1/resxpress#98]
In C#, it is common for keys to include underscores, for example, `UserType_Internal`. This character would be inherited by `<FileName>.Designer.cs`.

The change should be simple.

In extension.ts, on line 109, replace the following line:

```typescript
const sanitized = input.replace(/[^a-zA-Z0-9 ]/g, "");
```
with:

```typescript
const sanitized = input.replace(/[^a-zA-Z0-9_ ]/g, "");
```

Thanks!

**Comment by pmahend1** [comment]
Thanks for reporting. I added code to make keys Pascal cased, so I didn't think about _. 
Would you be able to create a PR with this change?

**Comment by manugparedes** [comment]
Done! #99
